### ISSUE TITLE
SASS, SCSS 등 CSS 전처리기 적용

### ISSUE THREAD

**Issue by goormdev** [eGovFramework/egovframe-template-simple-react#18]
CSS는 중복하여 작성하는 부분이 너무 많아 주로 SASS 등의 전처리기 등을 대신 이용합니다
예를 들어 src/css/page.css에 작성된 내용입니다
```css
.Plogin {padding-bottom: 100px;}
.Plogin h1 {color: #222; font-size: 48px; font-weight: 500; letter-spacing: -2px; line-height: 48px; text-align: center;}
.Plogin .txt {margin-top: 43px; color: #666; font-size: 20px; line-height: 30px; text-align: center;}
.Plogin .login_box {position: relative; width: 690px; margin: 54px auto 0; padding: 70px 95px ; border: 1px solid #dde2e5; border-radius: 25px; box-shadow: 3px 4px 5px #ccc;}
.Plogin .login_box .group {display: block; width: 320px;}
```

해당 내용을 SCSS의 대표적인 기능인 Nesting을 활용하여 작성하면 다음과 같습니다
```scss
.Plogin {
  padding-bottom: 100px;
  h1 {
    color: #222; font-size: 48px; font-weight: 500; letter-spacing: -2px; line-height: 48px; text-align: center;
  }

  .txt {
    margin-top: 43px; color: #666; font-size: 20px; line-height: 30px; text-align: center;
  }

  .login_box {
    position: relative; width: 690px; margin: 54px auto 0; padding: 70px 95px ; border: 1px solid #dde2e5; border-radius: 25px; box-shadow: 3px 4px 5px #ccc;

    .group {
      display: block; width: 320px;
    }
  }
}
```

CSS를 사용했을 때보다 선택자를 덜 적을 수 있고 구조가 잘 드러나게 됩니다.
적용하기 어렵지 않고 기존 CSS를 SASS, SCSS 등으로 변환하는 도구도 많이 나와있으니 활용하면 좋을 것 같습니다.
